language: node_js

node_js:
  - 12.7.0

os:
  - osx

jobs:
  include:
    - stage: check and test
      script: npm run format:ui -- --check
    - stage: build
      script: npm run build
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      before_deploy:
        - npm run build
        - export RELEASE_PKG_FILE=$(ls ./dist/*.*)
        - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file: dist/*
        overwrite: true
        skip_cleanup: true
        draft: true
        on:
          branch:
            - develop
            - master
          tags: true
